// front/vue-project/src/components/Tarjeta.vue
<script setup lang="ts">
import { computed } from 'vue'

const props = defineProps<{
  label: string
  value: string | number
  score: number
  trend: 'up' | 'down'
  companyName: string
  broker: string
}>()

const color = computed(() => {
  return props.trend === 'up'
    ? { bg: 'bg-green-100', text: 'text-green-600' }
    : { bg: 'bg-red-100', text: 'text-red-600' }
})
</script>

<template>
  <div class="flex items-end justify-between rounded-lg border border-gray-100 bg-white p-6">
    <div class="flex items-center gap-4">
      <span class="hidden rounded-full bg-gray-100 p-2 text-gray-600 sm:block">
        <svg xmlns="http://www.w3.org/2000/svg" class="size-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z"/>
        </svg>
      </span>

      <div>
        <p class="text-sm text-gray-500">{{ label }}</p>
        <p class="text-2xl font-medium text-gray-900">{{ value }}</p>
        <p class="text-sm text-gray-600">{{ companyName }}</p>
        <p class="text-sm text-gray-500">Broker: {{ broker }}</p>
      </div>
    </div>

    <div :class="`inline-flex gap-2 rounded-sm p-1 text-xs font-medium ${color.bg} ${color.text}`">
      <template v-if="trend === 'up'">
        <svg xmlns="http://www.w3.org/2000/svg" class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"/>
        </svg>
      </template>
      <template v-else>
        <svg xmlns="http://www.w3.org/2000/svg" class="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 17h8m0 0V9m0 8l-8-8-4 4-6-6"/>
        </svg>
      </template>
      <span>Score {{ score }}</span>
    </div>
  </div>
</template>

// front/react-project/src/components/Tarjeta.jsx
const Tarjeta = ({accion, tipo}) => {
    const bgColor = tipo === 'mejor' ? 'bg-green-100' : 'bg-red-100'
    const bgText = tipo === 'mejor' ? 'text-green-600' : 'text-red-600' 
    return(
        <>
        <div className="flex items-end justify-between rounded-lg border border-gray-100 bg-white p-6">
            <div className="flex items-center gap-4">
                <span className="hidden rounded-full bg-gray-100 p-2 text-gray-600 sm:block">
                <svg xmlns="http://www.w3.org/2000/svg" className="size-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth="2">
                    <path strokeLinecap="round" strokeLinejoin="round" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z" />
                </svg>
                </span>

                <div>
                <p className="text-sm text-gray-500">{tipo === 'mejor' ? 'Mejor Acción' : 'Peor Acción'}</p>
                <p className="text-2xl font-medium text-gray-900">{accion.ticker}  ${accion.target_to}</p>
                <p className="text-sm text-gray-600">{accion.company}</p>
                <p className="text-sm text-gray-500">Broker: {accion.brokerage}</p>
                </div>
            </div>

            <div className={`inline-flex gap-2 rounded-sm p-1 text-xs font-medium ${bgColor} ${bgText}`}>
                {tipo === 'mejor' ? (
                <svg xmlns="http://www.w3.org/2000/svg" className="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                </svg>
                ) : (
                <svg xmlns="http://www.w3.org/2000/svg" className="size-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 17h8m0 0V9m0 8l-8-8-4 4-6-6" />
                </svg>
                )}
                <span>Score: {accion.score}</span>
            </div>
        </div>

        </>
    )
}

export default Tarjeta
